version: "3.3"

services:
  backend:
    build: CNE-Final-Project/
    image: sashumi/javabackend:test
    restart: always
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - backend
    build: frontend/help_queue_p3/
    image: sashumi/nodefrontend:test
    restart: always
    ports:
      - "3000:3000"
    links:
      - backend
