apiVersion: v1
kind: Pod
metadata:
  name: help-queue
  namespace: production
  labels:
    app: help-queue
spec:
  containers:
  - name: frontend
    image: tayop/frontend:latest
    ports:
    - containerPort: 3000


apiVersion: v1
kind: Service
metadata:
  name: help-queue
  labels:
    app: help-queue
spec:
  selector:
    app: help-queue
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
