apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: production
  labels:
    app: nginx

spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: backend
  type: LoadBalancer

