apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: production
  labels:
    app: nginx

spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

