apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: production
data:
  default.conf:
    server {
        listen 80;
        location / {
            proxy_pass http://help-queue:3000;
        }
    }
    server {
        listen 8080;
        location / {
            proxy_pass http://backend:8080;
        }
    }
